### ISSUE TITLE
M-x helm Issues

### ISSUE THREAD

**Issue by likailejiacai** [baohaojun/system-config#3]
I saw the video and used your configuration . i used helm normally like this  
![screenshot from 2016-01-18 18-54-28](https://cloud.githubusercontent.com/assets/7688919/12389638/f3dc8edc-be14-11e5-8d8f-bd9269d3aa6f.png)
. When I need to write php, press the tab key, and the code can not make full prompt set-buffer: Wrong type argument: processp, nil Error running timer `ac-update-greedy ': (wrong-type-argument processp nil). I updated  plugins. M-x did not find the code hints 
![screenshot from 2016-01-18 18-09-38](https://cloud.githubusercontent.com/assets/7688919/12388992/00f7b87a-be11-11e5-9110-fc25c1d3d182.png)
A. These days reinstall the system, re-install the system-config several times, still can not be resolved. My system is ubuntu 15.10.

**Comment by baohaojun** [comment]
There should be no need to reinstall the system, and probably no need to re-install system-config. Seems you have met more than 1 problem? First, in php-mode, Tab key not working. Second, in M-x, seems Helm not working. I may advise you to attack these problems separately.

A wild guess is because melpa modules are not stable enough, and I myself have encountered several times where the Emacs becomes completely not usable after I update some plugins. But you really need to do some Emacs debugging by yourself to find out how best to handle it. Most of system-config's external plugins are installed by using ~/src/github/emacs.d, which is a fork of purcell's emacs.d IIRC., so you may modify files there to remove some problematic plugins.

By default, seems system-config will not install phh-mode, since I myself don't do php dev.
